#!/usr/bin/env python3
import sys
import common

def handler_common(args):
    try:
        if args.index:
            handler_index(args)
    except AttributeError:
        pass

_indexed = False
def handler_index(args):
    print('idx')
    global _indexed
    if _indexed:
        print("Warning: Attempt to index twice!")
        return
    _indexed = True
    return common.handler_none(args)

if __name__ == '__main__':
    parser = common.CommandParser(description='Suite of analysis tools for data generated by other tools in this repository.')
    parser.add_argument('-d', help='data directory')
    parser.add_argument('-i', '--index', default=False, action='store_true',
        help='automatically reindex first')

    parser_idx = parser.add_command('index', aliases=['idx'],
                help='Index files for use by other commands.',
                description='Index the files in the data directory by -bdw parameters for use by other analysis tools. For most output files, this process will succeed automatically, but where there are multiple jobs for a given parameter set you will be asked to manually resolve the ambiguity.')
    parser_idx.handler(handler_index)

    parser_hist = parser.add_command('histogram', aliases=['hist'],
                help='Generate histograms.')

    args = parser.parse_args()
    handler_common(args)
    args.handler(args)
